[package]
name = "grug-say"
version = "0.1.0"
edition = "2021"
authors = ["Holland Gibson (self aware smol brain) <dev@hollandgibson.com>"]

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
